name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: antlac1/aws-cost-reports

      - name: Build and push Docker image
        uses: docker/build-push-action@548776e8d0d44ea63feed0c8a944e6235fc63eee
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: antlac1/peertube-aws-remote-job-monitor:latest
          labels: ${{ steps.meta.outputs.labels }}